### ISSUE TITLE
resources key:DBClusterIdentifier on None

### ISSUE THREAD

**Issue by khalilgarnaoui** [cloud-custodian/community#60]
When running cloud custodian, I get this warning :
```
[WARNING]	2023-08-23T15:04:07.455Z	0d19afeb-3fbe-43ea-b2a4-6a572cb17eae	delete implicitly filtered 0 of 1 resources key:DBClusterIdentifier on None 
```
even though it filters the right resources : 
```
[DEBUG]	2023-08-23T15:04:07.454Z	0d19afeb-3fbe-43ea-b2a4-6a572cb17eae	Filtered from 1 to 1 rds
[INFO]	2023-08-23T15:04:07.454Z	0d19afeb-3fbe-43ea-b2a4-6a572cb17eae	policy:rds-delete-marked resource:rds region:eu-west-1 count:1 time:0.44"
```
Here are my policies : 

```
policies:
  - name: rds-mark-for-delete
    mode:
      type: periodic
      schedule: rate(1 day)
      role: arn:aws:iam::012345678901:role/custodian-tag-compliance-role
    resource: rds
    filters:
      - "tag:maid_status": absent
      - "tag:cost-center": absent
    actions:
      - type: mark-for-op
        op: delete
        days: 0

  - name: rds-delete-marked
    mode:
      type: periodic
      schedule: rate(1 day)
      role: arn:aws:iam::012345678901:role/custodian-tag-compliance-role
    resource: rds
    filters:
      - "tag:cost-center": absent
      - type: marked-for-op
        op: delete
    actions:
      - type: delete
        skip-snapshot: false
```
